var pics = [
//	[filenum,  'title', 'description', nonmacro]
	[0, 'Gold', '24kt gold flake on prong']
,	[1, 'Rigger', 'Unknown buildup on boat rigger']
,	[2, 'Crack', 'Crack in hull of boat, exposing carbon fiber underneath']
,	[3, 'Fraying', 'Fraying ends of carbon fiber (from broken boat hull)']
,	[4, 'Rust', 'Paint chipping on a utility pole shows the rust below']
,	[5, 'Fibers', 'Fibers in worn paper are visible at magnification']
,	[6, 'Aluminum', 'Detail on the surface of the Macbook Pro']
,	[7, 'DVDRW', 'Front side of DVDRW reflecting a 635nm laser']
,	[8, 'DVDRW II', 'Back side of DVDRW reflecting white light']
,	[9, 'Spectrum', 'The visible spectrum produced with a DVDRW']
,	[10, 'Center', 'The center of a Echeveria "dondo" derenbergii']
,	[11, 'Head', 'The head of a Pyrrharctia isabella larva ("wooly bear")']
,	[12, 'Extrusion', 'Liquid aluminum alloy extruded through glycerin']
,	[13, 'Bismuth', 'Brilliantly multicolored bismuth crystal']
,	[14, 'Bismuth II', 'Bismuth crystal, incl. abraded tip']
,	[15, 'Bismuth III', 'Bismuth crystal, detail of turquoise side']
,	[16, 'Glint', 'Bismuth crystal glinting in the sunlight']
,	[17, 'Bismuth IV', 'A darker background brings out purple hues']
,	[18, 'Bismuth V', 'Heavy spotting visible on this side']
,	[19, 'Bismuth VI', 'Nice rectangular structures visible']
,	[20, 'Bismuth VII', 'Inherently curved inner structure']
,	[21, 'Curlicue', 'Curled aluminum shaving left from drill press']
,	[22, 'Pancakes II', 'Stack of pancakes (top 3 detail)']
,	[23, 'Pancakes', 'Stack of pancakes']
,	[24, 'Pool', 'Pristine pool on a beautiful day']
,	[25, 'Pool II', 'Another view of the same pool, with palm trees']
,	[26, 'Leaf', 'Unknown leaf with dirt and dead patches']
,	[27, 'Twig & berry', 'Miniscule twig and accompanying berry']
,	[28, 'Mosses', 'Unidentified white and green mosses']
,	[29, 'Ground', 'Very high magnification picture of trail']
,	[30, 'Dark and light', 'Very high magnification picture of trail ground']
,	[31, 'Tiny spikes', 'Dead leaf with microscopic white spikes']
,	[32, 'Mosses II', 'Green mosses wrapping around flakes of bark']
,	[33, 'Mosses III', 'Mosses on a decaying log']
,	[34, 'Sealife I', 'Sea animals clinging to a glass barrier']
,	[35, 'Snake', 'Tiny snake pokes its head out of the sand']
]
